exports.SCHEDULE = {
  UPDATE_POST_VOTES: '05 */1 * * *',
  UPDATE_POST_CHILDREN: '20 */1 * * *',
  WAIVIO_WELCOME: '20 6 */1 * *',
  WAIVIO_API_CACHE_HIVE_PRICE: '0 */1 * * * *',
  WAIVIO_API_SERVICE_BOTS: '30 14 */1 * *',
  WAIVIO_API_COLLECT_APP_EXPERTS: '30 14 */1 * *',
  WAIVIO_API_COLLECT_WOBJECT_EXPERTS: '30 9 */1 * *',
  WAIVIO_API_IMPORT_USERS: '0 */1 * * *',
  WAIVIO_API_IMPORT_ERROR_USERS: '0 */10 * * *',
  WAIVIO_API_SEND_WEBSITE_DAILY_DEBT: '0 0 */1 * *',
};
