exports.SCHEDULE = {
  UPDATE_POST_VOTES: '05 */1 * * *',
  UPDATE_POST_CHILDREN: '20 */1 * * *',
  WAIVIO_WELCOME: '20 6 */1 * *',
  WAIVIO_API_CACHE_HIVE_PRICE: '0 */1 * * * *',
  WAIVIO_API_SERVICE_BOTS: '30 14 */1 * *',
  WAIVIO_API_COLLECT_APP_EXPERTS: '30 14 */1 * *',
};
