exports.REDIS_KEY = {
  EXPIRE_CLIENT: 'expirePost',
  VOTE_UPDATES: 'votesUpdate',
  CHILDREN_UPDATE: 'commentsCounterUpdate',
  DISTRIBUTE_HIVE_ENGINE_REWARD: 'distributeHiveEngineReward',
  SMT_POOL: 'smt_pool',
  REWARD_FUND: 'reward_fund',
  CURRENT_MEDIAN_HISTORY_PRICE: 'current_median_history_price',
  CACHE_SERVICE_BOTS: 'service_bots',
  TOP_WOBJ_USERS_KEY: 'topUsers',
  IMPORTED_USER: 'import_user:',
  IMPORTED_USER_ERROR: 'import_user_error:',
  SITE_USERS_STATISTIC: 'siteUsers',
  WAIVIO_ADMINS: 'waivio_admins',
  WEBSITE_SUSPENDED_COUNT: 'website_suspended_count',
  BLOCK: 'test:hive:blocks',
  POST: 'test:hive:post',
  HISTORY: 'test:hive:history',
  REQUESTS_RATE_API: 'requests:api:',
  REQUESTS_RATE_WARNING_LIMIT: 'requests:warning_limit',
  ENGINE_NODES_LIST: 'engine_nodes_list',
};
